# Generated by Django 3.0.8 on 2020-09-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_logtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='inital_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
