# Generated by Django 3.0.8 on 2020-09-09 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200909_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='inital_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 19, 46, 52, 496094)),
        ),
    ]
