# Generated by Django 3.0.8 on 2020-09-09 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200909_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='inital_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 14, 33, 9, 296081, tzinfo=utc)),
        ),
    ]
